config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # MA: 'responses' view route via URL
  resources :responses

  # Defines the root path route ("/")
  # MA: Application default view
  root "responses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/response.rb
class Response < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: %i[ show edit update destroy ]

  # MA: Sortable table columns [http://railscasts.com/episodes/228-sortable-table-columns]
  helper_method :sort_column, :sort_direction

  # GET /responses or /responses.json
  def index
    # MA: Sortable table columns [http://railscasts.com/episodes/228-sortable-table-columns]
    # MA: Filtering implementation [https://activerecord-hackery.github.io/ransack/getting-started/simple-mode/]
    @q = Response.ransack(params[:q])
    @responses = @q.result().order(sort_column + " " + sort_direction)

    # MA: Chartkick-based piechart (filterable) [https://chartkick.com/]
    @chart_responses = @q.result()
  end

  # GET /responses/1 or /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses or /responses.json
  # MA: (Excel) ="Response.create!("&$B$2&": "&CHAR(34)&$B4&CHAR(34)&", "&$C$2&": "&$C4&", "&$D$2&": "&$D4&", "&$E$2&": "&$E4&", "&$F$2&": "&CHAR(34)&$F4&CHAR(34)&", "&$G$2&": "&$G4&", "&$H$2&": "&$H4&", "&$I$2&": "&$I4&", "&$J$2&": "&$J4&", "&$K$2&": "&$K4&", "&$L$2&": "&CHAR(34)&$L4&CHAR(34)&", "&$M$2&": "&CHAR(34)&$M4&CHAR(34)&")"
  # MA: (irb>)  Response.create!(undergrad_continent: "Europe", hb_a_1_1: 10, hb_a_2_1: 50, hb_a_3_1: 300, dem_1: "A lot (e.g. \"I have thought enough to have my own views on the topic\")", vb_1_1: 64, vb_1_2: 20, vb_1_3: 3, vb_1_4: 3, vb_1_5: 10, dem_2: "A lot (e.g. \"I have thought enough to have my own views on the topic\")", sr_1: "More")
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to response_url(@response), notice: "Response was successfully created." }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1 or /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to response_url(@response), notice: "Response was successfully updated." }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1 or /responses/1.json
  def destroy
    @response.destroy

    respond_to do |format|
      format.html { redirect_to responses_url, notice: "Response was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def response_params
      params.require(:response).permit(:undergrad_continent, :hb_a_1_1, :hb_a_2_1, :hb_a_3_1, :dem_1, :vb_1_1, :vb_1_2, :vb_1_3, :vb_1_4, :vb_1_5, :dem_2, :sr_1)
    end
  
    # MA: Sortable table columns [http://railscasts.com/episodes/228-sortable-table-columns]
    def sort_column
      Response.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # MA: Sortable table columns attempt [http://railscasts.com/episodes/228-sortable-table-columns]
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
      end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTreinings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/_form.html.erb
<%= simple_form_for(@response) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :undergrad_continent %>
    <%= f.input :hb_a_1_1 %>
    <%= f.input :hb_a_2_1 %>
    <%= f.input :hb_a_3_1 %>
    <%= f.input :dem_1 %>
    <%= f.input :vb_1_1 %>
    <%= f.input :vb_1_2 %>
    <%= f.input :vb_1_3 %>
    <%= f.input :vb_1_4 %>
    <%= f.input :vb_1_5 %>
    <%= f.input :dem_2 %>
    <%= f.input :sr_1 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/responses/_response.html.erb
<div id="<%= dom_id response %>">
  <p>
    <strong>Undergrad continent:</strong>
    <%= response.undergrad_continent %>
  </p>

  <p>
    <strong>Hb a 1 1:</strong>
    <%= response.hb_a_1_1 %>
  </p>

  <p>
    <strong>Hb a 2 1:</strong>
    <%= response.hb_a_2_1 %>
  </p>

  <p>
    <strong>Hb a 3 1:</strong>
    <%= response.hb_a_3_1 %>
  </p>

  <p>
    <strong>Dem 1:</strong>
    <%= response.dem_1 %>
  </p>

  <p>
    <strong>Vb 1 1:</strong>
    <%= response.vb_1_1 %>
  </p>

  <p>
    <strong>Vb 1 2:</strong>
    <%= response.vb_1_2 %>
  </p>

  <p>
    <strong>Vb 1 3:</strong>
    <%= response.vb_1_3 %>
  </p>

  <p>
    <strong>Vb 1 4:</strong>
    <%= response.vb_1_4 %>
  </p>

  <p>
    <strong>Vb 1 5:</strong>
    <%= response.vb_1_5 %>
  </p>

  <p>
    <strong>Dem 2:</strong>
    <%= response.dem_2 %>
  </p>

  <p>
    <strong>Sr 1:</strong>
    <%= response.sr_1 %>
  </p>

</div>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Show this response", @response %> |
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/index.html.erb
<p style="color: green"><%= notice %></p>

<% # MA: Aggregate metric table: %>
<div>
  <table class="content-table">
    <thead>
      <tr>
        <td>Metric (n=<%= @responses.count %>)</td>
        <td>hb_a_1_1</td>
        <td>hb_a_2_1</td>
        <td>hb_a_3_1</td>
        <td>vb_1_1</td>
        <td>vb_1_2</td>
        <td>vb_1_3</td>
        <td>vb_1_4</td>
        <td>vb_1_5</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Median</td>
        <td><%= 2022 + @responses.median(:hb_a_1_1).round() %></td>
        <td><%= 2022 + @responses.median(:hb_a_2_1).round() %></td>
        <td><%= 2022 + @responses.median(:hb_a_3_1).round() %></td>
        <td><%= @responses.median(:vb_1_1).round(1) %>%</td>
        <td><%= @responses.median(:vb_1_2).round(1) %>%</td>
        <td><%= @responses.median(:vb_1_3).round(1) %>%</td>
        <td><%= @responses.median(:vb_1_4).round(1) %>%</td>
        <td><%= @responses.median(:vb_1_5).round(1) %>%</td>
      </tr>
      <tr>
        <td>Average</td>
        <td><%= 2022 + @responses.average(:hb_a_1_1).round() %></td>
        <td><%= 2022 + @responses.average(:hb_a_2_1).round() %></td>
        <td><%= 2022 + @responses.average(:hb_a_3_1).round() %></td>
        <td><%= @responses.average(:vb_1_1).round(1) %>%</td>
        <td><%= @responses.average(:vb_1_2).round(1) %>%</td>
        <td><%= @responses.average(:vb_1_3).round(1) %>%</td>
        <td><%= @responses.average(:vb_1_4).round(1) %>%</td>
        <td><%= @responses.average(:vb_1_5).round(1) %>%</td>
      </tr>
    </tbody>
  </table>
</div>

<% # MA: Chartkick-based piechart [https://chartkick.com/] %>
<div>
  <%= pie_chart @chart_responses.group(:sr_1).count, title: "sr_1" %>
  <% #= pie_chart @responses.reorder('').group(:sr_1).count %>
</div>

<%= link_to "New response", new_response_path %>

<% # MA: Filtering implementation [https://activerecord-hackery.github.io/ransack/getting-started/simple-mode/] %>
<div>
  <%= search_form_for @q, url: :responses do |form| %>
    <%= form.label :undergrad_continent_cont %>
    <%= form.search_field :undergrad_continent_cont %>
    <%= form.submit %>
  <% end %>
</div>

<% # MA: Drop down filter HTML table data by column attempt: %>
<% #= collection_select :response, :id, Response.all, :id, :undergrad_continent, prompt: true %>

<% # MA: Display database records in HTML table: %>
<div id="responses">
  <% # MA: Sortable table columns [http://railscasts.com/episodes/228-sortable-table-columns] %>
  <table id="responses" class="content-table">
    <thead>
      <tr>
        <td>id</td>
        <td>undergrad_continent</td>
        <td>hb_a_1_1</td>
        <td>hb_a_2_1</td>
        <td>hb_a_3_1</td>
        <td>dem_1</td>
        <td>vb_1_1</td>
        <td>vb_1_2</td>
        <td>vb_1_3</td>
        <td>vb_1_4</td>
        <td>vb_1_5</td>
        <td>dem_2</td>
        <td>sr_1</td>
      </tr>
      <tr>
        <th><%= sortable "id", "Response ID" %></th>
        <th><%= sortable "undergrad_continent", "In which region did you complete your undergraduate study?" %></th>
        <th><%= sortable "hb_a_1_1", "For the purposes of this question, assume that human scientific activity continues without major negative disruption.
          \n\nHow many years until you expect a 10% probability of HLMI existing?" %></th>
        <th><%= sortable "hb_a_2_1", "For the purposes of this question, assume that human scientific activity continues without major negative disruption.
          \n\nHow many years until you expect a 50% probability of HLMI existing?" %></th>
        <th><%= sortable "hb_a_3_1", "For the purposes of this question, assume that human scientific activity continues without major negative disruption.
          \n\nHow many years until you expect a 90% probability of HLMI existing?" %></th>
        <th><%= sortable "dem_1", "How much thought have you given in the past to when HLMI (or something similar) will be developed?" %></th>
        <th><%= sortable "vb_1_1", "Assume for the purpose of this question that HLMI will at some point exist.
          \n\nHow positive or negative do you expect the overall impact of this to be on humanity, in the long run?
          \n\nPlease answer by saying how probable you find the following kinds of impact, with probabilities adding to 100%: Extremely good (e.g. rapid growth in human flourishing)" %></th>
        <th><%= sortable "vb_1_2", "Assume for the purpose of this question that HLMI will at some point exist.
          \n\nHow positive or negative do you expect the overall impact of this to be on humanity, in the long run?
          \n\nPlease answer by saying how probable you find the following kinds of impact, with probabilities adding to 100%: On balance good" %></th>
        <th><%= sortable "vb_1_3", "Assume for the purpose of this question that HLMI will at some point exist.
          \n\nHow positive or negative do you expect the overall impact of this to be on humanity, in the long run?
          \n\nPlease answer by saying how probable you find the following kinds of impact, with probabilities adding to 100%: More or less neutral" %></th>
        <th><%= sortable "vb_1_4", "Assume for the purpose of this question that HLMI will at some point exist.
          \n\nHow positive or negative do you expect the overall impact of this to be on humanity, in the long run?
          \n\nPlease answer by saying how probable you find the following kinds of impact, with probabilities adding to 100%: On balance bad" %></th>
        <th><%= sortable "vb_1_5", "Assume for the purpose of this question that HLMI will at some point exist.
          \n\nHow positive or negative do you expect the overall impact of this to be on humanity, in the long run?
          \n\nPlease answer by saying how probable you find the following kinds of impact, with probabilities adding to 100%: Extremely bad (e.g. human extinction)" %></th>
        <th><%= sortable "dem_2", "How much thought have you given in the past to social impacts of smarter-than-human machines?" %></th>
        <th><%= sortable "sr_1", "How much should society prioritize AI safety research, relative to how much it is currently prioritized?" %></th>
      </tr>
    </thead>
    <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= link_to(response.id, response) %></td>
        <td><%= response.undergrad_continent %></td>
        <td><%= response.hb_a_1_1 %></td>
        <td><%= response.hb_a_2_1 %></td>
        <td><%= response.hb_a_3_1 %></td>
        <td><%= response.dem_1 %></td>
        <td><%= response.vb_1_1 %></td>
        <td><%= response.vb_1_2 %></td>
        <td><%= response.vb_1_3 %></td>
        <td><%= response.vb_1_4 %></td>
        <td><%= response.vb_1_5 %></td>
        <td><%= response.dem_2 %></td>
        <td><%= response.sr_1 %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @response %>

<div>
  <%= link_to "Edit this response", edit_response_path(@response) %> |
  <%= link_to "Back to responses", responses_path %>

  <%= button_to "Destroy this response", @response, method: :delete %>
</div>